// Class automatically generated by Dev-C++ New Class wizard

#include "aeropuerto.h" // class's header file

// class constructor
/*aeropuerto::aeropuerto(ColadeAviones**x(cavion**, int c), int tam2)
{
tam=tam2;
vec=new ColadeAviones*[tam];
for(int i=0;i<tam;i++)
{
       (*(vec+i))=(*(x+i));
}
}*/

// class destructor
aeropuerto::~aeropuerto()
{
	// insert your code here
}
ColadeAviones UnirColas();
void aeropuerto::MostrarUnaSolaCola(int pos)
{(*(vec+pos))->mostrar();}
