// Class automatically generated by Dev-C++ New Class wizard

#ifndef AEROPUERTO_H
#define AEROPUERTO_H
#include "coladeaviones.h"
// No description
class aeropuerto:public ColadeAviones
{ColadeAviones**vec;
int tam;
	public:
		// class constructor
		aeropuerto(ColadeAviones**x, int);
		// class destructor
		~aeropuerto();
		ColadeAviones UnirColas();
        void MostrarUnaSolaCola(int pos);
};

#endif // AEROPUERTO_H
