// Class automatically generated by Dev-C++ New Class wizard

#ifndef ANGULO_H
#define ANGULO_H
#include <iostream.h>
#include <conio.h>
// No description
class angulo
{
int grado;
int minuto;
int segundo;
char orientacion;
	public:
		// class constructor
		angulo(int,int,int,char);
		angulo();
		// class destructor
		~angulo();
		int getgrado();
		int getminuto();
		int getsegundo();
		char getorient();
		void setgrado(int);
		void setminuto(int);
		void setsegundo(int);
		void setorient(char);
		void operator=(angulo);
		bool operator==(angulo);
		void mostrar();
};

#endif // ANGULO_H
