// Class automatically generated by Dev-C++ New Class wizard

#ifndef AVIONDCARGA_H
#define AVIONDCARGA_H
#include "cavion.h" 
// No description
class avionDcarga:public cavion
{long cargaTons;
long cargaVol;
	public:
		// class constructor
		avionDcarga(string cod,coordenana n,hora h,long min,long tons,long vol);
		// class destructor
		~avionDcarga();
		void mostrar();
};

#endif // AVIONDCARGA_H
