// Class automatically generated by Dev-C++ New Class wizard

#include "avion.h" // class's header file

// class constructor
avion::avion(string cod,coordenana n,hora hd,long min)
{
codigo=cod;
//c=n;
//horasalida=hd;
minutosDemora=min;
}
avion::avion()
{
	// insert your code here
}

// class destructor
avion::~avion()
{
	// insert your code here
}
void avion::mostrar()
{cout<<"Codigo:         "<<codigo<<endl;
cout<<"Coordenada de destino:         "<<endl;}
/*c.mostrar();
}
	hora CalcularHoraLlegada();// que calcula la hora de llegada.
	void CambiarCoordenadasDestino(coordenada, coordenada);// que cambia las coordenadas de destino.
	void CambiarAnguloLongitud(angulo); //que cambia el ángulo "longitud" de las coordenadas de destino.
	void CambiarAnguloLatitud(angulo);*/
