// Class automatically generated by Dev-C++ New Class wizard

#include "avionbombero.h" // class's header file

// class constructor
avionBombero::avionBombero(string cod,coordenana n,hora h,long min,long tanq,long lit)
:cavion(cod,n,h,min)
{
numeroDtanques=tanq;
Capacidadlitros=lit;
}

// class destructor
avionBombero::~avionBombero()
{
	// insert your code here
}
void avionBombero::mostrar()
{
cavion::mostrar();
cout<<"Cantidad de tanquies:                  "<<numeroDtanques<<endl;
cout<<"Capacidad en litros P/tanque:           "<<Capacidadlitros<<endl;
}
