// Class automatically generated by Dev-C++ New Class wizard

#ifndef AVIONBOMBERO_H
#define AVIONBOMBERO_H
#include "cavion.h" 
// No description
class avionBombero:public cavion
{long numeroDtanques;
long Capacidadlitros;
	public:
		// class constructor
		avionBombero(string cod,coordenana n,hora h,long min,long tanq,long lit);
		// class destructor
		~avionBombero();
		void mostrar();
};

#endif // AVIONBOMBERO_H
