// Class automatically generated by Dev-C++ New Class wizard

#include "aviondcarga.h" // class's header file

// class constructor
avionDcarga::avionDcarga(string cod,coordenana n,hora h,long min,long tons,long vol)
:cavion(cod,n,h,min)
{
cargaTons=tons;
cargaVol=vol;
}

// class destructor
avionDcarga::~avionDcarga()
{
	// insert your code here
}
void avionDcarga::mostrar()
{
//cavion::mostrar();
cout<<"Carga en Toneladas:       "<<cargaTons<<endl;
cout<<"Carga en Vols:           "<<cargaVol<<endl;
}
