// Class automatically generated by Dev-C++ New Class wizard

#ifndef CAVION_H
#define CAVION_H



#include <cstdlib>
#include <iostream.h>
#include <string.h>
#include "hora.h"
#include "coordenana.h"
using namespace std;

class cavion
{
protected:
string codigo;
coordenana c;
hora horasalida;
long minutosDemora;

	public:
		// class constructor
		cavion(string,coordenana n,hora h,long);
		// class constructor
		cavion();
		// class destructor
		~cavion();
	void mostrar();
    // que muestra toda la información del avión.
	hora CalcularHoraLlegada();// que calcula la hora de llegada.
	void CambiarCoordenadasDestino(coordenana);// que cambia las coordenadas de destino.
	void CambiarAnguloLongitud(angulo); //que cambia el ángulo "longitud" de las coordenadas de destino.
	void CambiarAnguloLatitud(angulo);
	string getCodigo();
	void operator=(cavion);
	bool operator==(cavion);
};

#endif // CAVION_H
