// Class automatically generated by Dev-C++ New Class wizard

#include "cavion.h" // class's header file
#include "hora.h"
#include "coordenana.h"

// class constructor
cavion::cavion(string cod,coordenana n,hora h,long min)
{
codigo=cod;
c=n;
horasalida.igualA(h);
minutosDemora=min;
}
cavion::cavion()
{
	// insert your code here
}

// class destructor
cavion::~cavion()
{
	// insert your code here
}
void cavion::mostrar()
{
cout<<"Codigo:         "<<codigo<<endl;
cout<<"Coordenada de destino:         "<<endl;
c.mostrar();cout<<endl;
cout<<"Tiempo de demora en min:    "<<minutosDemora<<endl;
}

hora cavion::CalcularHoraLlegada()
    {return horasalida.calcularHoraLlegada(horasalida, minutosDemora);}
void cavion::CambiarCoordenadasDestino(coordenana x)
    {c=x;}
void cavion::CambiarAnguloLongitud(angulo x)
    { c.setLongitud(x);}
void cavion::CambiarAnguloLatitud(angulo y)
    {c.setLatitud(y);
    }
    string cavion::getCodigo()
    {return codigo;}
void cavion::operator =(cavion a)
{codigo=a.codigo;
c=a.c;
horasalida.igualA(a.horasalida);
minutosDemora=a.minutosDemora;
}
bool cavion::operator ==(cavion a)
{
if(codigo==a.codigo && c==a.c && horasalida==a.horasalida && minutosDemora==a.minutosDemora)
return 1;
else
return 0;
}
