// Class automatically generated by Dev-C++ New Class wizard

#ifndef COORDENANA_H
#define COORDENANA_H
#include "angulo.h" 
#include <conio.h>
#include <iostream.h>
// No description
class coordenana
{angulo longitud;
angulo latitud;
	public:
		// class constructor
		coordenana(int,int,int,char,int,int,int,char);
		coordenana(angulo lo, angulo la);
		coordenana();
		// class destructor
		~coordenana();
		angulo getlongit();
		angulo getlatit();
		void setLatitud(angulo);
		void setLongitud(angulo);
		void setcoordenada(int,int,int,char,int,int,int,char);
		void operator=(coordenana);
		bool operator==(coordenana);
        void mostrar();

};

#endif // COORDENANA_H
