// Class automatically generated by Dev-C++ New Class wizard

#ifndef HORA_H
#define HORA_H
#include <iostream.h>
#include <conio.h>
#include <windows.h>
// No description
class hora
{int hor;
int minuto;
int segundo;
	public:
		// class constructor
		hora(int, int, int);
		hora();
		// class destructor
		~hora();
		int gethor();
		int getmin();
		int getseg();
		hora calcularHoraLlegada(hora inic, long min);
		void igualA(hora);
		bool operator==(hora);
		void mostrar();
};

#endif // HORA_H
