// Class automatically generated by Dev-C++ New Class wizard

#include "hora.h" // class's header file

// class constructor
hora::hora(int h, int m, int s)
{hor=h;
minuto=m;
segundo=s;

}
hora::hora()
{
	// insert your code here
}

// class destructor
hora::~hora()
{
	// insert your code here
}
int hora::gethor()
{return hor;}
int hora::getmin()
{return minuto;}
int hora::getseg()
{return segundo;}
hora hora::calcularHoraLlegada(hora inic, long min)
{long inici=(inic.gethor()*3600)+(inic.getmin()*60)+inic.getseg();
long demora=min*60;
cout<<demora<<endl;
cout<<inici<<endl;
long final=inici+demora;
cout<<final<<endl;
hora llegada;
llegada.hor=final/3600;
if(llegada.hor>24)
llegada.hor=final/3600-24;
llegada.minuto=(final-(final/3600*3600))/60;

llegada.segundo=(final-(final/3600*3600)-((final-(final/3600*3600))/60*60));
return llegada;
}
void hora::igualA(hora h)
{hor=h.gethor();
minuto=h.getmin();
segundo=h.getseg();
}
bool hora::operator==(hora a)
{if(hor==a.hor&&minuto==a.minuto&&segundo==a.segundo)
return 1;
else
return 0;
}
void hora::mostrar()
{
     
	if(hor<10)
	{
		cout<< "0"<<hor;
	}
	else
	{
		cout<< hor;
	}
    if(minuto<10)
	{
		cout<< ":0"<<minuto;
	}
	else
	{
		cout<< ":"<<minuto;
	}
	if(segundo<10)
	{
		cout<< ":0"<<segundo;
	}
	else
	{
		cout<< ":"<<segundo;

	}
	
}     
